fixtures:
  repositories:
    stdlib:
      repo: "https://github.com/Adaptavist/puppet-stdlib"
    host_core:
      repo: "https://github.com/puppetlabs/puppetlabs-host_core"
  symlinks:
    'definer': "#{source_dir}"
